### ISSUE TITLE
setting location tag for mqtt subscribe

### ISSUE THREAD

**Issue by hjoertel** [mattzzw/obi_socket#8]
the variable unique_machine_id used in mqtt subscribe command should configurable by the SETUP menue by the user. So it will be possible to give location names like "living room", "kitchen", whatever.

**Comment by mattzzw** [comment]
Agreed, that would make sense.
I want to make all fields of the json config file editable by the user anyway.

**Comment by mattzzw** [comment]
OK, all settings are now editable in the SETUP menu.
@hjoertel - please close the ticket if the solution is ok. 
(However, you might run into issue #7)
